### ISSUE TITLE
[Request] Configure web base URL for CI results 

### ISSUE THREAD

**Issue by stefanhoth** [novoda/gradle-static-analysis-plugin#10]
I'm basing this feature request on my previous experience and the output shown in the Readme. It may be this is already obsolete. 

When running static analyses  the output always refers to local file URLs for reports which is fine on a local machine but unusable for CI logs.
Since it's hard(er) to guess the environment the CI job runs in I propose the easier solution of adding a configuration value to use as a base URL to access the reports via browser on a remote machine.

**Comment by eduardb** [comment]
@stefanhoth maybe this Chrome extension from @danybony will come in handy: https://chrome.google.com/webstore/detail/jenkins-relative-links/mhdpelbikeadhkopckfnfofkghioembf

**Comment by stefanhoth** [comment]
@eduardb Thanks for the pointer. I still think we could solve this in a more general manner.

**Comment by mr-archano** [comment]
The PR #25 introduces the feature. A new version of the plugin will be rolled out soon, and a recipe about the integration with Jenkins will be included in the repo documentation.

**Comment by rock3r** [comment]
This was done as part of #25
