### ISSUE TITLE
Merging the results in a multi-module environment

### ISSUE THREAD

**Issue by tasomaniac** [novoda/gradle-static-analysis-plugin#111]
At the moment in a multi-module setup, `evaluateViolations` task will run individually on each Gradle project. They have no way of communicate to each other. When multiple modules fail, it is somewhat hard to identify which ones have been failed. Especially when `--continue` param is used. 

Also in such scenario, `maxErrors` does not make much sense individually for each submodule. It would only makes sense when `maxErrors = 0` (simply because  `0 * noOfModules = 0`)

Defining a root level task that will collect all the results from each task from subprojects and give a single report would be nice.

**Comment by mr-archano** [comment]
Good idea @tasomaniac, I have thought about this in the past, and I reckon that making the `EvaluteViolationsTask` to accept files as input (maybe as part of #43) will make this easier.

**Comment by tasomaniac** [comment]
Aha! #43 sounds good. (Although I don't understand my last comment now 🙂)

I'm not sure about the implementation of this task at the moment. I guess it is something to figure out. But the output will definitely be helpful.

**Comment by tasomaniac** [comment]
Btw, according to these tips about lint performance from Tor Noybe, it is recommended to run lint check only on the `app` module with `checkDependencies` turned on. 

https://groups.google.com/forum/#!msg/lint-dev/RGTvK_uHQGQ/FjJA12aGBAAJ

This also automatically merges the results.

I think we should merge results from all tools anyways but this tip from `lint` is also something additional to consider.
