### ISSUE TITLE
New option: "failFast"

### ISSUE THREAD

**Issue by tasomaniac** [novoda/gradle-static-analysis-plugin#112]
When running multiple tools `evaluateViolations` run all configured tools and output the result at the end. 

A new `failFast` option could stop the build just after a configured tool has done its job and has errors.

**Comment by tasomaniac** [comment]
Fair enough :) Plugin has many features. 

My favorite feature is that it makes it easier to setup everything. Especially for Android. Title and description of README also says the same 😛 

I think `failFast` is just a preference. Why not support both?

**Comment by rock3r** [comment]
I'm not against that, mind me, but the point of the plugin is that it evaluates failures against a global threshold; if you fail fast (based on what? _any_ error? because all tools are set up to allow infinite errors since we need to collect them) how can you do that?

**Comment by tasomaniac** [comment]
In most of the cases, you can know that the build is certainly gonna fail. 

This is true especially when the `maxErrors=0`. A single error will make it fail. 

It is also the case when a single tool already exceeds the threshold.

**Comment by rock3r** [comment]
Again, I am not against this, but it seems like a lot of change for little gain, is all

**Comment by tasomaniac** [comment]
Not sure if it requires lot of change.

**Comment by tasomaniac** [comment]
Looks like we are addressing #164 and that voids the need of the flag mentioned here. Will go ahead and close this one.
