### ISSUE TITLE
Lint exclude support 

### ISSUE THREAD

**Issue by ouchadam** [novoda/gradle-static-analysis-plugin#116]
Seems like the lint configurator doesn't support the exclude functionality, would be great if it did!

**Comment by rock3r** [comment]
I don't think Lint supports that outside of the configuration XML, that may be the reason

**Comment by tasomaniac** [comment]
Maybe we should make that clear in the docs.

**Comment by mr-archano** [comment]
@ouchadam I need to look into that, but I assume Lint uses a different way of dealing with that. We can attempt to do something as crazy as synthetising an XML for Lint if that is needed!

**Comment by rock3r** [comment]
@mr-archano that would be crazy and overcomplicated... I like it 💃
