### ISSUE TITLE
"Global" exclude filters

### ISSUE THREAD

**Issue by takecare** [novoda/gradle-static-analysis-plugin#14]
How hard would it be to have the exclude filters apply to all configurations?

Example:
```
staticAnalysis {
    penalty {
        maxErrors = 0
        maxWarnings = 10
    }
    checkstyle {
        configFile project.file('path/to/modules.xml')
    }
    pmd {
        ruleSetFiles project.files('path/to/rules.xml')
    }
    findbugs {
        excludeFilter project.file('path/to/exclude.xml')
    }
    all {
        exclude project.fileTree('src/test/java')
    }
}
```

Having the same practical effect as having `exclude project.fileTree('src/test/java')` in each configuration.

**Comment by mr-archano** [comment]
It's totally feasible @takecare, good idea 👍 .
Let me put this in our backlog so to plan when to spend some time on it.

**Comment by tasomaniac** [comment]
This can also be done for `includeVariants` filter. I checked some of our internal projects and saw that we use different `includeVariants` for different tools but also we share too. 

But still, it would be really good to have a common `includeVariants` in case where the project wants to run all tools, let's say, only on `playDebug` variant
