### ISSUE TITLE
Support error-prone

### ISSUE THREAD

**Issue by tasomaniac** [novoda/gradle-static-analysis-plugin#151]
Add support for error prone: https://github.com/google/error-prone

Error prone is a java compiler. Errors and warnings come as compilation errors and warnings. It does not have support for reports.

So, we need to find a way to support it nicely into our current system.

**Comment by bitsydarel** [comment]
Would be amazing, If report could be added.

**Comment by mr-archano** [comment]
Yeah @bitsydarel the tricky bit with error-prone is that reporting is done in console as far I know, I never spent much time thinking of a possible way of solving that (although I guess we could request some change upstream and then support it). Any idea is welcome of course :)
