### ISSUE TITLE
Add per-tool evaluation

### ISSUE THREAD

**Issue by georgi-neykov-hub** [novoda/gradle-static-analysis-plugin#164]
First of all a big thank you for the effort on the plugin and making and making it open source. 

Are you considering adding the option to have an violation collection and evaluation tasks for each tool? It would be of great convenience and it would allow running tasks for the different tools in parallel in a CI environment. For example, in v0.8.0 of the plugin there is no way to evaluate only the errors for Checkstyle, I would prefer stopping a CI build from running unit tests, lint, ... and other heavy tasks if there style problems with the source files .

**Comment by tasomaniac** [comment]
Hi, if you have Gradle parallel builds available, running `evaluateViolations` should run all other tools in parallel already.

I created this issue a while ago for fail fast option. I think this captures what you want to do. 
https://github.com/novoda/gradle-static-analysis-plugin/issues/112

I put some thoughts onto this and it is not super easy. It is easy to make individual tools fail the build as early as possible, but then it is not so easy to have consistent reports at the end.

**Comment by mr-archano** [comment]
Hi @georgi-neykov-hub we've been discussing about having per-tool reporting in the past and as @tasomaniac we haven't found a strategy that makes us happy yet.

I believe that we could tackle this in separate steps, starting for instance with addressing #43 (`Use file output to store violations per tool`), combined with a custom evaluator (introduced in  #45 and documented in [`docs/incubating/custom-evaluator.md`](https://github.com/novoda/gradle-static-analysis-plugin/blob/master/docs/incubating/custom-evaluator.md)).
