### ISSUE TITLE
Run check for a particular flavor/build type

### ISSUE THREAD

**Issue by bblackbelt** [novoda/gradle-static-analysis-plugin#198]
Hi, 

 would it be possible to run `gradlew check` for a specific combination of flavors/build type ?

EG.

`   gradlew checkFlavorDebug`

thanks

**Comment by tasomaniac** [comment]
Hi, in the configuration, you have the option to filter per variant. It gives you the whole variant object where you can filter per flavor or buildType (debug/release). Sample project's build.gradle has an example. 

If you do this, you need to run evaluateViolations task and that will do that for you.
