### ISSUE TITLE
Make the plugin Gradle Kotlin DSL friendly

### ISSUE THREAD

**Issue by tasomaniac** [novoda/gradle-static-analysis-plugin#210]
Currently, we are depending on a lot of Groovy features. It works really well since it supports variety of code quality plugins without knowing the internal implementation details of them.

While keeping this plugin implementation in Groovy, we can make the DSL usage more kotlin friendly.

**Comment by mr-archano** [comment]
@tasomaniac it would be nice to have examples of the kind of improved DSL we are seeking.

**Comment by tasomaniac** [comment]
I guess we should create a Gradle Kotlin sample. It is not really usable at all. I wonder if we have any users with Kotlin DSL. They may shed some light.

**Comment by AdamMc331** [comment]
I tried to do this, but currently I noticed it's not working. I don't think I realized it doesn't work. When I use this set up, it marks the `./gradlew evaluateViolations` task as successful but it doesn't actually run any of the tooling: https://github.com/AdamMc331/PokeDex/blob/917f9255ceefeb27b0e27b3cd528c6eb03cdc642/build.gradle.kts#L36-L67

Curious if anyone has been able to make this work.

**Comment by tasomaniac** [comment]
ktlint and detekt configurations are just functions. In this example, they run with the outer context. They configure the plugins just fine. Unfortunately static-analysis plugin is not aware. 

With groovy, that works since we use some Groovy magic.

**Comment by AdamMc331** [comment]
Does this mean using Kotlin DSL it's completely unsupported? Or does something stand out that I'm missing?

**Comment by tasomaniac** [comment]
Right now, yes, it is unsupported. This issue is all about making it work.

**Comment by AdamMc331** [comment]
Gotcha. I am going to switch my project to run ktlint/detekt individually for right now, but please ping me if I can ever provide any support. I don't know much about building gradle plugins, but since I have that sample app ready I can help test any time.

**Comment by tasomaniac** [comment]
Another option for Kotlin Gradle users would be to extract all static analysis configuration to a separate Groovy file and just use `apply` function in your `build.gradle.kts`
