### ISSUE TITLE
Make Violations class and reports more informative

### ISSUE THREAD

**Issue by maxbach** [novoda/gradle-static-analysis-plugin#219]
There are should be more info in Violations. It should be added list of Errors and Warnings. Every warning and error has a description, type, file and line in file, where it is located. Then it will be possible to create custom reports. For example, create report to console or Logcat with list of errors and every error will have a link to code with error.

For example, 
![image](https://user-images.githubusercontent.com/5735956/69530079-7cab7d00-0f82-11ea-98cc-1e17ba683ebf.png)

**Comment by mr-archano** [comment]
Hi @maxbach, thanks for the suggestion but I am not sure this should be this tool behaviour. This plugin is simply configuring other plugins, each of them using different ways of identifying and reporting violations of different nature.
The value that this plugin wants to provide is not unified reporting, but rather:
- out-of-the box support for Android projects
- allow to run all the checks and decide what is an unacceptable TOTAL amount of violations

Providing what you are suggesting is definitely feasible but I believe that we should keep the detailed reporting to each tool (we still link the reports in our output).

**Comment by msal98** [comment]
I'm finding that if I use the Checkstyle plugin directly I see violations in the console (very helpful). However, through this plugin I'm only seeing a link to the report. Does this fall under the "making violations more informative", or is this worthy of it's own issue?

**Comment by tasomaniac** [comment]
Hi, since static analysis plugin consolidates all results, it changes some console output settings. The reason is to make the console output shorter. 

Can you try to configure the Checkstyle plugin to output more? You can try doing it in

```
staticAnalysis {
    checkstyle {
        showViolations = true
    } 
}
```
