### ISSUE TITLE
all unit tests fail

### ISSUE THREAD

**Issue by stealthrabbi** [novoda/gradle-static-analysis-plugin#224]
Checking out the project and running `./gradlew build` runs the tests and nearly all fail.

**Comment by tasomaniac** [comment]
Can you give more details about the errors you get. It must be a local configuration issue. Every PR is checked in Jenkins CI.

Closing this for now. Please give more details and I am glad to help resolve the issue you have.

**Comment by stealthrabbi** [comment]
Hi. I'm using an openjdk, 1.8.0_231, x64, on windows 10

Gradle wrapper is targeting gradle-5.5.1-all.zip
