### ISSUE TITLE
SpotBugs fails due to null path variable

### ISSUE THREAD

**Issue by stealthrabbi** [novoda/gradle-static-analysis-plugin#225]
This is from running the multi-proj sample with ./gradlew build. I am getting teh same error on my own project when attempting to use this plugin

> Task :app:spotbugsDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:spotbugsDebugAndroidTest'.
> path may not be null or empty string. path='null'

**Comment by stealthrabbi** [comment]
I've seen documentation somewhere about force-setting the sourceSets for the android module like so:

```
sourceSets {
    // we define `main` sourceSet here, so SpotBugs Gradle Plugin generates `spotbugsMain` task
    main {
        java.srcDirs = ['src/main/java']
    }
}
```

this does not work, as it causes an issue with pmd:

```
* Where:
Script 'C:\Projects\myproj\static-analysis.gradle' line: 22

* What went wrong:
A problem occurred evaluating script.
> Cannot add task 'pmdMain' as a task with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by tasomaniac** [comment]
Hi. I'm not sure why SpotBugs documentation asks people to add a sourceSet but that is hacky and would never work on Android.

Which version of Gradle ve JDK are you using?

**Comment by stealthrabbi** [comment]
Hi. I'm using an openjdk, 1.8.0_231, x64.

Gradle wrapper is targeting gradle-5.5.1-all.zip

**Comment by stealthrabbi** [comment]
My android gradle plugin version is 3.5.0

**Comment by stealthrabbi** [comment]
Upgarading my gradle wrapper from 5.5.1 to target 5.6.4 (final gradle 5.x release) allowed me to run pmd and spotbugs via your plugin successfully. I suspect this issue was something with spotbugs itself, although I don't know what upgrading gradle and not spotbugs would do for me (i'm still on spotbugs 3.0).

Honestly this web of versions and dependencies with JDK, android sdk, gradle, android gradle plugin, and all these tools is a headache!

**Comment by tasomaniac** [comment]
Perhaps SpotBugs dropped support for some of 5.x Gradle releases. Our plugin supports even Gradle 4.x with no problem. 

If you use newer versions of other plugins, you must use the version they support. Unfortunately, these are not very well documented.

**Comment by mikemee** [comment]
Thanks @stealthrabbi - I was having the same error in Android Studio, and upgrading to 5.6.4 in the `gradle/wrapper/gradle-wrapper.properties` files (by using the File -> Project Structure ... dialog) got it working for me.  _(Now, if I can just get HTML instead of XML reports working!)_
