### ISSUE TITLE
How to enable HTML reports for SpotBugs?

### ISSUE THREAD

**Issue by mikemee** [novoda/gradle-static-analysis-plugin#227]
I'm upgrading from FindBugs to SpotBugs (version 3.0.0) and I'd like to get `html` reports instead of `xml`. 

After digging around ([here](https://github.com/spotbugs/spotbugs-gradle-plugin/issues/32)), I was able to add this to my `gradle.build` file to generate HTML:

```groovy
// To generate an HTML report instead of XML
tasks.withType(com.github.spotbugs.SpotBugsTask) {
  reports {
    xml.enabled = false
    html.enabled = true
  }
}
```
I'm wondering if I missed some other way, or if perhaps the plugin requires a similar work around to FindBugs (like #117 et al)?

**Comment by tasomaniac** [comment]
Hi, we kept the setup really the same when replacing Findbugs in this project.

First of all, you don't need to get the task. Our plugin supports putting `reports` block directly under `spotbugs { }` configuration.

On top of that, our plugin enables HTML reports by default. Normally, SpotBugs does not support having both XML and HTML reports at the same time. That's why we had to introduce additional to control this behavior.

**Comment by mikemee** [comment]
@tasomaniac Thanks!  I did try SpotBugs with no specification for reports (i.e. just like the FindBugs configuration) and it was consistently generating XML reports until I added the above.

I had also tried adding `reports` like this:

```gradle
    spotbugs {
        reports {
            xml.enabled = false
            html.enabled = true
        }
    }
```
and that gives a configuration error.
```
* What went wrong:
A problem occurred evaluating project ':app'.
> A problem occurred while configuring SpotBugs.
```

Happy to provide more info if that would help.  I have plugins specified as:
```gradle
    id 'com.novoda.static-analysis' version '1.2'
    id "com.github.spotbugs" version '3.0.0'
```

**Comment by worktj** [comment]
@mikemee  This works for me:
```
    spotbugs {
        toolVersion = '4.0.3'
        effort = 'default'
        reportLevel = 'high'
    }

    [spotbugsMain, spotbugsTest].each { task ->
        task.configure {
            reports {
                html {
                    enabled = true
                    stylesheet = 'fancy-hist.xsl'
                }
            }
        }
    }
```

**Comment by mikemee** [comment]
Thanks for the tips. I think the latest version of SpotBugs is working as expected now. Closing this to avoid distracting everyone. I'll re-open / open a new issue if I find anything else along these lines.
