### ISSUE TITLE
Findbugs HTML report not generated

### ISSUE THREAD

**Issue by xrigau** [novoda/gradle-static-analysis-plugin#24]
With a standard project set up, when I run `gradlew check`, if the build fails due to static analysis issues it prints the following lines:

```
> Violations limit exceeded by 0 errors, 1 warnings.
  
  > Checkstyle rule violations were found (461 errors, 54 warnings). See the reports at:
  - file:///Users/xrigau/Desktop/fooproject/app/build/reports/checkstyle/main.html
  > Findbugs rule violations were found (10 errors, 50 warnings). See the reports at:
  - file:///Users/xrigau/Desktop/fooproject/app/build/reports/findbugs/fooprojectDebug.html
  > PMD rule violations were found (126 errors, 587 warnings). See the reports at:
  - file:///Users/xrigau/Desktop/fooproject/app/build/reports/pmd/main.html
```

But actually the `fooprojectDebug.html` file doesn't exist and only an XML file is created:

![screen shot 2017-02-15 at 3 57 46 pm](https://cloud.githubusercontent.com/assets/1626673/22979707/94091ac0-f397-11e6-956a-31f13614a402.png)

**Comment by mr-archano** [comment]
Looked into this with @xrigau over screen hero, it was a project-specific configuration issue.
