### ISSUE TITLE
Lazy evaluate exclude filters

### ISSUE THREAD

**Issue by mr-archano** [novoda/gradle-static-analysis-plugin#34]
At the moment the `exclude` filter does not support any lazy evaluation so values are evaluated at configuration time. Ideally `SourceFilter` would be amended to add support to closures.

**Comment by mr-archano** [comment]
@devisnik do you reckon that the issue we discussed the other day about the wrapping `staticAnalysis{}` can be related to this?

**Comment by tasomaniac** [comment]
Thanks to the new Lazy Task configuration, exclude are now also lazily applied. Closing this as it is resolved.
