### ISSUE TITLE
Missing files dues to new dependency graph

### ISSUE THREAD

**Issue by pablisco** [novoda/gradle-static-analysis-plugin#40]
The new way of resolving dependencies by Gradle 4.4 and android Gradle Plugin 3.0.1 means that some of the dependencies are not available when analysing.

In order to solve this we need an option to ignore third party classes: `-auxclasspath classpath` 

Reference: https://stackoverflow.com/a/13363381/458365

**Comment by mr-archano** [comment]
Is this a warning or a fatal error? Could you provide a branch showcasing the issue? It should be quite easy to write another integration test reproducing the issue.

**Comment by mr-archano** [comment]
There is no further info provided for this, and I'm incline to think the issue is not in the plugin unless proved otherwise with a sample. Feel free to comment/reopen with more information if still relevant.
