### ISSUE TITLE
Use file output to store violations per-tool

### ISSUE THREAD

**Issue by mr-archano** [novoda/gradle-static-analysis-plugin#43]
Right now the plugin stores the violations in an in-memory `NamedDomainObjectContainer` holding an instance of `Violations` for each of the tool configured. Ideally each tool would instead produce an (xml?) report that can be used as input of the `EvaluateViolationsTask`. This would also help with the incremental builds, as an input/output file plays nicer with Gradle architecture.

**Comment by tasomaniac** [comment]
You can define custom Objects to be input/output too. With `Property` and `Provider`s. (Are they Gradle 4+?) I think they also need to be Serializable then. The incremental build mechanism works like the same. Writing to a file may not be necessary.

**Comment by mr-archano** [comment]
@tasomaniac good point, but then 2 things come to mind:
- 1. I don't see why we should loose retro-compatibility, even though Gradle 4.x is widely adopted already
- 2. I feel like having the output as persisted report can open possibilities we haven't fully figured out yet, even though we can always write the objects as files if we need to

Mmmm.

**Comment by tasomaniac** [comment]
That may makes sense for other purposes of course. Since all the tools integrated already has output files, it could also be an overhead to have even more files. ☺
