### ISSUE TITLE
[RFC] Static analysis tools: Opting-in vs Opting-out

### ISSUE THREAD

**Issue by mr-archano** [novoda/gradle-static-analysis-plugin#5]
At the moment the plugin is not opting in any of the static analysis tools supported. To enable one of them you need to explicitly provide a configuration for the tool of choice. For instance, having this in your build script:
```
staticAnalysis {
    checkstyle {
        configFile project.file 'blah'
    }
}
```
will only enable Checkstyle, while PMD and FindBugs will be not. The rationale of this choice is that you need anyway a minimal setup for such tools to use them, like providing a configuration file. This unfortunately doesn't apply to FindBugs, where no minimal configuration is required, forcing you to have something ugly like:
```
staticAnalysis {
    checkstyle {
        configFile project.file 'blah'
    }
    findbugs {} // this empty config :puke:
}
```

How do we want to evolve this? Should we move to opting-out all the tools and exposing an API to disable them if needed? What do you reckon is the average case?
Let's discuss.

**Comment by eduardb** [comment]
I think that an opt-out approach would be better because:
 - it would make people use more of the tools included in this plugin (it's less likely that they will opt-out)
 - probably one would want to use all the tools anyway if he is using this plugin

**Comment by blundell** [comment]
also +1 for the opt-out approach.

If you think of Donar organ transplants, currently England is opt-in with a low rate of something like 15% , Wales just changed the law to be opt-out therefore starting at a rate of 100% which saves a lot of lives.

We should also save lives.

**Comment by mr-archano** [comment]
Ok, it seems we have a consensus here. Let's enable all the tools by default. My only concern now is the minimal setup needed to make everything work out of the box, for instance you must specify a config file for Checkstyle otherwise the build will fail.
What we can do is enabling the opt-out once we have support for the artifact with rules, because at that point we can ship a preconfigured setup that users can tweak as needed.

Thoughts?

**Comment by blundell** [comment]
yes we want to keep setup minimum.

Can we have smallest set of default rules in the plugin with a log message saying "e - no rules specified falling back on minimal, non-advised defaults" or something. Maybe this is what `because at that point we can ship a preconfigured setup that users can tweak as needed` means

**Comment by mr-archano** [comment]
Shipping a setup means adding support for rules. no big deal, I've [already done that|https://github.com/mr-archano/static-analysis-plugin/blob/master/plugin/src/main/groovy/com/archano/gradle/staticanalysis/StaticAnalysisPlugin.groovy#L13-L21] and it works great. Will focus on this as first step.

**Comment by rock3r** [comment]
@mr-archano is this still relevant?

**Comment by mr-archano** [comment]
Nah @rock3r, we have taken a decision already and - altho I am still confused by `opt-in` vs `opt-out` meaning - I believe we can roll with what we have and iterate as needed.

**Comment by tasomaniac** [comment]
👍 Btw, I don't think empty closure if ugly at all. It is the same with product flavors.
