### ISSUE TITLE
Add support for KtLint for Kotlin projects

### ISSUE THREAD

**Issue by rock3r** [novoda/gradle-static-analysis-plugin#50]
KtLint is a code formatting and static analysis tool for Kotlin. Since Kotlin adoption is growing fast, and the classic trifecta of static analysis plugins don't work with it, it would be nice to have some tool that covers Kotlin code too.

See https://github.com/shyiko/ktlint

**Comment by tasomaniac** [comment]
Just worked on this in the morning. TDD FTW!!!

PR coming soon.

**Comment by rock3r** [comment]
AWESOME! Thanks Tahsin :)

**Comment by tasomaniac** [comment]
Should we close this? Actually it would be great to have some docs. I can do that but master is ahead of develop.

**Comment by mr-archano** [comment]
It looks like this has been addressed fully via #110 and #124
