### ISSUE TITLE
Update default tools versions to latest

### ISSUE THREAD

**Issue by rock3r** [novoda/gradle-static-analysis-plugin#52]
Currently we default to Checkstyle 7.1.2 and PMD 5.5.1, which are quite old (from September and July 2016, respectively). At the time of writing, Checkstyle is at version 8.8 and PMD at 6.0.1.

**Comment by tasomaniac** [comment]
Would that be a breaking change? I mean, to make PMD versioned to 6.x by default?

**Comment by rock3r** [comment]
It's not a breaking change in the plugin or its API, it's a change on the ruleset side for PMD — but it will work. They have deprecated the old rules but besides printing a gazillion warnings in the stdout it will still work.

**Comment by mr-archano** [comment]
What should we do with this? to be honest I _kinda_ regret that we are not using the default versions of each tool - unless there's a very good reason to not use the ones shipped in the Gradle distribution.
