### ISSUE TITLE
Trying to configure `lintOptions` twice fails

### ISSUE THREAD

**Issue by tasomaniac** [novoda/gradle-static-analysis-plugin#84]
### Problem 

In bigger projects, it is common practice to let other `gradle` files setup such configurations. This means that the common configuration around `lintOptions` would be applied not in the `build.gradle` but somewhere else.

But still individual `lintOptions` configurations can have additional configuration. Even though this should be done very careful, it may be needed for bigger projects. 

When `lintOptions` is used within static-analysis plugin, we try to create and configure tasks 2 times. And build fails because the tasks already exist. 

### Suggested Fix: 

To overcome this, we can check if task exists first, or we can use `maybeCreate`

**Comment by tasomaniac** [comment]
This commit showcases the problem with a test-case. https://github.com/novoda/gradle-static-analysis-plugin/commit/b36a992920268b78450e4e784f4f8ca7fe3d3414

Here is also the screenshot of the failure:

<img width="1239" alt="screen shot 2018-02-15 at 10 35 46 am" src="https://user-images.githubusercontent.com/763339/36249970-b48be52e-123c-11e8-8a21-141b0ca7a43d.png">

**Comment by mr-archano** [comment]
Nice catch @tasomaniac, we probably should always prefer to use `maybeCreate`.

**Comment by tasomaniac** [comment]
It seems that the same problem exists for all tools. I will add the same test case to the other tools. But I'm not sure how easy it would be to fix the others since they're more complicated.

**Comment by tasomaniac** [comment]
Fixed by #89
