### ISSUE TITLE
Strange intermittent crash on Jenkins CI

### ISSUE THREAD

**Issue by hydro0** [novoda/gradle-static-analysis-plugin#98]
When running a build on Jenkins machine from times to times a crash raises when collecting `pmd`. If that is important - `pmd` violation number is zero in that cases. Any ideas what can be wrong? Thanks.

```
* What went wrong:
Execution failed for task ':android:android-library:collectPmdMainViolations'.
> Bad <init> method call from inside of a branch
  Exception Details:
    Location:
      com/novoda/staticanalysis/internal/pmd/PmdViolationsEvaluator.<init>(Ljava/io/File;)V @83: invokespecial
    Reason:
      Error exists in the bytecode
```

java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

Mac OS Sierra 10.12.6

**Comment by takecare** [comment]
@hydro0 can you update your java runtime and check if it still happens?

**Comment by mr-archano** [comment]
Thanks for this @hydro0, I will try to add a test with zero pmd violations and see if I can reproduce the issue. Couple more questions to help us troubleshoot the issue:
- What version of Gradle are you using in your project?
- Would you be able to provide a sample project that reproduces the issue?

**Comment by hydro0** [comment]
Hey guys,
Thanks for the quick response. Actually, the update of java version to `1.8.0_161` solved the issue. So, do you still need the Gradle version for that? I think that can be closed as java issue, but just if someone will receive the same issue, they'll know they have to upgrade.

**Comment by mr-archano** [comment]
@hydro0 glad that you solved your issue, there's no need to put more effort on this if you have found a way to make it work.
